### PR TITLE
chore(*): Bumps bindle to use the 2021 edition

### PR DESCRIPTION
**Pull request by thomastaylor312**
We've been tracking and using most of the latest features anyway, so
this seems to make sense

### CODE REVIEW

**Comment by thomastaylor312** [comment]
NOTE: This cannot be merged until Github actions updates to 1.56

**Comment by radu-matei** [comment]
We could manually `rustup install` and `default` to 1.56 in the meantime, if we wanted to.

**Comment by thomastaylor312** [comment]
Yeah, we could use actions-rs to install the right version

**Comment by thomastaylor312** [comment]
@radu-matei This is ready for re-review. The cargo deny stuff is handled in another PR

**Review by technosophos — APPROVED** [review]
It appears that GH Actions are now at the right version (see comments). So I think this is good to merge?

**Review by radu-matei — APPROVED** [review]
LGTM

**Pull request merged**
