### PR TITLE
feat: push docker image

### PR DESCRIPTION
**Pull request by FrankYang0529**
ref: https://github.com/fermyon/installer/issues/63, https://github.com/fermyon/installer/pull/100#issuecomment-1276462821

### CODE REVIEW

**Comment by FrankYang0529** [comment]
@microsoft-github-policy-service agree [company="default"]

**Comment by FrankYang0529** [comment]
@microsoft-github-policy-service agree

**Review by vdice — COMMENTED** [review]
Defer to the code owners for final decision, but I'm wondering if we want to push to this repo's GitHub container registry instead (`ghcr.io/deislabs/bindle`)?  We should be able to use the default `$GITHUB_TOKEN` to [push images](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry).

**Comment by FrankYang0529** [comment]
> Defer to the code owners for final decision, but I'm wondering if we want to push to this repo's GitHub container registry instead (`ghcr.io/deislabs/bindle`)? We should be able to use the default `$GITHUB_TOKEN` to [push images](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry).

Yeah, I think it's good to use the default `$GITHUB_TOKEN` and we don't need to maintain docker credentials. Thanks. Updated it!

**Review by vdice — APPROVED** [review]
Nice, I appreciate how this enables forks to test/run this same workflow as well 👍

**Pull request merged**
